let locations: string[] = ['Ireland', 'Canada', 'Bali', 'Germany', 'Azerbaijan']
console.log(`Original order: "${locations}"`)
console.log(`\nAlphabetical order: "${locations.slice().sort()}"`)
console.log(`Original order: "${locations}"`)
console.log(`\nReverse alphabetical order: "${locations.slice().sort().reverse()}"`)
console.log(`Original order: "${locations}"`)
console.log(`\nReversed order: "${locations.reverse()}"`)
console.log(`\nOriginal order again: "${locations.reverse()}"`)
console.log(`\nSorted alphabetical order: "${locations.sort()}"`)
console.log(`\nSorted reverse alphabetical order: "${locations.reverse()}"`)
